export const siteConfig = {
  name: "DSN Akvaryum",
  fullName: "DSN Akvaryum İmalatı",
  brandLabel: "DSN AKVARYUM İMALATI",
  logoPath: "/images/dsn-logo.jpeg",
  demo: process.env.NEXT_PUBLIC_DEMO_MODE !== "false",
  url: process.env.SITE_URL || "",
  whatsapp: process.env.WHATSAPP_NUMBER || "",
  phone: "0545 389 71 47",
  phoneHref: "tel:+905453897147",
  address: "Mamak Hüseyin Gazi, Ekin, Su Sk. No:17, 06160 Mamak/Ankara",
  socialHandle: "Dursun_belgic",
  email: "",
  hours: "",
  aquariumGlass: "DIAMOND cam",
  customProductionVerified: false,
  dimensionLimits: { min: 10, max: 300 },
};
